model_type: cnn
hyperparameters:
  lr: [0.001, 0.002, 0.004, 0.006, 0.01, 0.014, 0.022, 0.034, 0.051, 0.078]
  conv_channels: [2, 4, 6, 8]
  dropout: [0.05]
  n_layers: [1, 2, 3, 4, 5, 6]

settings:
  total_cpus: 1
  total_gpus: 0
  num_samples: 2

