model_type: ffnn
hyperparameters:
  lr: [0.0001, 0.0005, 0.001, 0.002, 0.006, 0.01, 0.022, 0.04, 0.06]
  hidden_dim: [8, 16, 32, 64]
  dropout: [0.05, 0.1, 0.15]
  n_layers: [2, 3, 4, 5, 6]
  batch_size: [128, 512]

knob_settings:
  p: [0.1, 0.15, 0.2]

settings:
  total_cpus: 100
  num_samples: 300
  total_gpus: 0


