model_type: gnn
hyperparameters:
  lr: [0.00001, 0.00005, 0.0001, 0.0005, 0.001, 0.002]
  batch_size: [128, 256]
  gcn_depth: [3, 5]
  gcn_min: [16, 32, 64]
  mlp_depth: [3]
  mlp_max: [128, 64]

knob_settings:
  beta: [1.1, 1.05]

settings:
  total_cpus: 2
  num_samples: 2
  total_gpus: 0


