model_type: gnn
hyperparameters:
  lr: [ 0.0002, 0.0003, 0.0004]
  batch_size: [512, 1024]
  gcn_depth: [4, 5, 6]
  gcn_min: [32, 64]
  mlp_depth: [3, 4]
  mlp_max: [128]
  n_train: [1048576]

knob_settings:
  beta: [14, 15, 16, 17, 18]

settings:
  total_cpus: 75
  num_samples: 75
  total_gpus: 0
