model_type: gnn
hyperparameters:
  lr: [ 0.0002, 0.0003, 0.0004]
  batch_size: [512, 1024]
  gcn_depth: [4, 5, 6]
  gcn_min: [32, 64]
  mlp_depth: [3, 4]
  mlp_max: [128]
  n_train: [131072, 262144, 524288, 1048576, 2097152, 4194304, 8388608]

knob_settings:
  beta: [1, 2, 3]

settings:
  total_cpus: 1
  num_samples: 1
  total_gpus: 0
