model_type: gnn
hyperparameters:
  lr: [0.0001, 0.0002, 0.0003]
  batch_size: [512, 1024]
  gcn_depth: [5, 6, 7]
  gcn_min: [32, 64]
  mlp_depth: [3, 4]
  mlp_max: [128, 256]
  n_train: [131072, 262144, 524288, 1048576]

knob_settings:
  beta: [1, 2]

settings:
  total_cpus: 100
  num_samples: 200
  total_gpus: 0
